### ISSUE TITLE
你的配置图标显示不全是缺哪个字体？装了几个都不是，囧

### ISSUE THREAD

**Issue by flyingns** [wenjinnn/config#1]
![Screenshot_20211118_184816](https://user-images.githubusercontent.com/16456728/142401695-6429f526-3fdf-4ebf-82a7-d653ee5eb3d1.png)

![Screenshot_20211118_185114](https://user-images.githubusercontent.com/16456728/142401892-09d34ad5-87e1-4040-8213-5ea05788a2bf.png)

感谢。

**Comment by wenjinnn** [comment]
需要修补字体
https://github.com/ryanoasis/nerd-fonts
releases页选一个你喜欢的字体安装然后设置就好
等会儿我会补充这个到readme
