### ISSUE TITLE
已装了下面一些字体，并没有改变，可以获取乱码字符的字体信息吗？

### ISSUE THREAD

**Issue by flyingns** [wenjinnn/config#2]
![Screenshot_20211119_120507](https://user-images.githubusercontent.com/16456728/142563325-d1d82dcf-2ac2-43de-bb6c-029c91889a5d.png)
![Screenshot_20211118_185114](https://user-images.githubusercontent.com/16456728/142563330-0626d40b-4bc3-466f-9e2f-c8cc52393f26.png)

**Comment by wenjinnn** [comment]
你应该是安装了没有设置，在终端模拟器里要设置一下安装的字体
比如我设置的是FiraCode Nerd Font Mono

**Comment by flyingns** [comment]
暈，腦筋打結了，一時沒想到這個。囧
