### ISSUE TITLE
多用户

### ISSUE THREAD

**Issue by xxb** [wenjinnn/config#3]
这套配置只有一个用户wenjin
如果需要多个用户貌似要改动很多

**Comment by wenjinnn** [comment]
这套配置确实不考虑多用户，所以gteetd默认取第一个用户，要改的话auth.ts用户名的组件改成输入框其他地方也相应的改一下就行了，不想折腾建议换用gdm
想支持多用户的话本身就很多工作，按nix的方式如果你想每个用户配置差异化，还得各维护一套home manager的配置
